export const posts = [
  {
    id: 1,
    title: 'How Sade Sati Can Reshape a 3-Year Life Cycle',
    slug: 'sade-sati-3-year-cycle',
    excerpt:
      'Understand Saturn’s phases, common pitfalls, and simple remedies to stay balanced through Sade Sati.',
    category: 'Sade Sati',
    tags: ['Saturn', 'Transit', 'Remedies'],
    author: 'SriAstroVeda Editorial',
    datePublished: '2025-08-12',
    dateModified: '2025-08-20',
    readingTime: 6,
    image: '/images/posts/sade-sati.jpg',
    featured: true,
  },
  {
    id: 2,
    title: 'Love Compatibility by Nakshatra: What Really Matters',
    slug: 'love-compatibility-nakshatra',
    excerpt:
      'A practical guide to compatibility signals from Moon Nakshatras and what to prioritize in partnerships.',
    category: 'Love Life',
    tags: ['Compatibility', 'Nakshatra', 'Relationships'],
    author: 'SriAstroVeda Editorial',
    datePublished: '2025-07-28',
    dateModified: '2025-08-02',
    readingTime: 7,
    image: '/images/posts/love-nakshatra.jpg',
    featured: true,
  },
  {
    id: 3,
    title: 'Dasha Periods and Career Decisions: Timing Moves',
    slug: 'dasha-career-decisions',
    excerpt:
      'Map career choices to Dasha and Bhukti transitions to reduce risk and amplify momentum at the right time.',
    category: 'Dasha',
    tags: ['Mahadasha', 'Career', 'Timing'],
    author: 'SriAstroVeda Editorial',
    datePublished: '2025-08-30',
    dateModified: '2025-08-30',
    readingTime: 5,
    image: '/images/posts/dasha-career.jpg',
    featured: false,
  },
  {
    id: 4,
    title: 'Choosing Gemstones: Dos, Don’ts, and Timing',
    slug: 'choosing-gemstones-dos-donts',
    excerpt:
      'Avoid common pitfalls in gemstone selection, and learn when to start, pause, or switch a stone.',
    category: 'Gemstones',
    tags: ['Remedies', 'Guides'],
    author: 'SriAstroVeda Editorial',
    datePublished: '2025-08-22',
    dateModified: '2025-08-25',
    readingTime: 4,
    image: '/images/posts/gemstones.jpg',
    featured: false,
  },
  {
    id: 5,
    title: 'Numerology for 2025: Personal Year Patterns',
    slug: 'numerology-2025-personal-year',
    excerpt:
      'Decode personal year vibrations for 2025 and spot months that favor health, wealth, and relationships.',
    category: 'Numerology',
    tags: ['2025', 'Forecast'],
    author: 'SriAstroVeda Editorial',
    datePublished: '2025-09-01',
    dateModified: '2025-09-01',
    readingTime: 6,
    image: '/images/posts/numerology-2025.jpg',
    featured: false,
  },
];
